# -*- coding: utf-8 -*-
"""Machine learning

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zqcQCGiFA2tAzXiGjQhDjGILV30s8VIV
"""

import nltk
from nltk.chat.util import Chat, reflections
reflections = {
    "I am": "You are",
    "I was": "You were",
    "I": "You",
    "I'm": "You are",
    "I'd": "You would",
    "I've": "You have",
    "I'll": "You will",
    "my": "Your",
    "You are": "I am",
    "You were": "I was",
    "You've": "I have",
    "You'll": "I will",
    "Your": "My",
    "You":"Me",
    "Me": "You"
}
pairs = [
    [
        r"my name is (.*)",
        ["Hello%1,How are you today?"]
    ],
    [
        r"hi|hey|hello",
        ["Hello","Hey there"]
    ],
    [
        r"What is your name?",
        ["I am bot created using python and NTLK."]

    ],
    [
        r"How are you?",
        ["I'm doing good. how about you?"]
    ],
    [
        r"sorry(.*)",
        ["Its alright","Its Ok, never mind"]
    ],
    [
        r"I am fine",
        ["Great to hear that, how can I help you?"]

    ],
    [
        r"(.*)age?",
        ["I'm an computer program. I don't have any age."]
    ],
    [
        r"what(.*)want",
        ["Make me an offer I can't refuse"]
    ],
    [
        r"(.*)created",
        ["I was created using python's nltk library,"]
    ],
    [
        r"(.*)(location|city)?",
        ["I live inside computer system."]
    ],
    [
        r"how is weather in (.*)?",
        ["Weather in %1 is awesome like always."]
    ],
    [
        r"quit",
        ["Bye!Take care."]

    ],

]
chat = chat(pairs,reflections)

print("Hi! I am your chatbot. Type 'quit' to exit.")

chat.converse()